# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 量潮身份与访问管理Django工具箱
author: 量潮科技


# Information about where the book exists on the web
repository:
  url: https://github.com/quanttide/django-quanttide-idam  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.autosummary'
  config:
    autosummary_generate: True
